general improvements to the git-sync script
mostly related to output

diff --git a/bash/git-sync b/bash/git-sync
--- a/bash/git-sync
+++ b/bash/git-sync
@@ -92,7 +92,7 @@ then
 fi
 
 # fetch the latest from the remote branch
-git fetch ${remote} ${remote_branch}
+git fetch ${remote} ${remote_branch} &> /dev/null
 if [[ $? != 0 ]]
 then
     >&2 echo -e "${error_color}error: failed to fetch from ${remote}${no_color}"
@@ -100,8 +100,8 @@ then
 fi
 
 # ensure the local repository is current with the origin remote
-git fetch origin
-git remote prune origin
+git fetch origin &> /dev/null
+git remote prune origin &> /dev/null
 
 # record the current branch, so we can switch back to it later
 current_branch="$(git rev-parse --abbrev-ref HEAD)"
@@ -110,63 +110,65 @@ current_branch="$(git rev-parse --abbrev-ref HEAD)"
 # 1. check if merging remote/remote_branch has conflicts
 # 2. if no conflicts, merge and push
 # 3. append the branch to the appropriate result list
-branches=($(git for-each-ref --format="%(refname:short)" refs/heads/*))
-conflicted_branches=()
-pushed_branches=()
-failed_branches=()
+branches=($(git for-each-ref --format="%(refname:lstrip=3)" refs/remotes/origin/**))
+branches=(${branches[@]/HEAD})
+
+length=${#branches[0]}
+
 for branch in ${branches[@]}
 do
-    git checkout ${branch}
+    if [[ ${#branch} -gt ${length} ]]
+    then
+        length=${#branch}
+    fi
+done
+
+printf "%-${length}s  Check Out    Origin Merge  Upstream Merge  Push\n" "Branch"
+
+for branch in ${branches[@]}
+do
+    printf "%-${length}s  " ${branch}
+    git checkout ${branch} &> /dev/null
+    if [[ $? -ne 0 ]]
+    then
+        printf "${error_color}failed${no_color}\n"
+    else
+        printf "checked out  "
+    fi
 
     # merge the origin upstream. if this causes conflicts, there's nothing else
     # to be done
-    git merge --no-edit origin/${branch}
+    git merge --no-edit origin/${branch} &> /dev/null
     conflicts=($(git diff --name-only --diff-filter=U))
     if [[ ${#conflicts[@]} != 0 ]]
     then
-        conflicted_branches+=(${branch})
-        git merge --abort
+        printf "${error_color}conflicted${no_color}\n"
+        git merge --abort &> /dev/null
     else
+        printf "merged        "
         # merge from the specified remote ref. again, if conflicts result,
         # abandon the update for this branch.
-        git merge --no-edit ${remote_ref}
+        git merge --no-edit ${remote_ref} &> /dev/null
         conflicts=($(git diff --name-only --diff-filter=U))
         if [[ ${#conflicts[@]} != 0 ]]
         then
-            conflicted_branches+=(${branch})
-            git merge --abort
+            printf "${error_color}conflicted${no_color}\n"
+            git merge --abort &> /dev/null
         else
-            git push origin ${branch}
+            printf "merged        "
+            git push origin ${branch} &> /dev/null
             if [[ $? == 0 ]]
             then
-                pushed_branches+=(${branch})
+                printf "pushed\n"
             else
-                failed_branches+=(${branch})
+                printf "${error_color}failed${no_color}\n"
             fi
         fi
     fi
 done
 
 # now go back to the original branch the user was on
-git checkout ${current_branch}
+git checkout ${current_branch} &> /dev/null
 
-# output results summary
-echo
-echo "these branches were merged & pushed:"
-for branch in ${pushed_branches[@]}
-do
-    echo -e "    ${success_color}${branch}${no_color}"
-done
-echo
-echo "these branches merged, but failed to be pushed"
-for branch in ${failed_branches[@]}
-do
-    echo -e "    ${error_color}${branch}${no_color}"
-done
-echo
-echo "these branches have merge conflicts:"
-for branch in ${conflicted_branches[@]}
-do
-    echo -e "    ${error_color}${branch}${no_color}"
-done
 exit 0
+
